/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Liveness and keep-warm. Never calls ORS, never throttled.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `1` - 1
         * @enum {string}
         */
        ApiVersionEnum: "1";
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            field?: string;
            details?: components["schemas"]["FieldError"][];
            retry_after_s?: number;
            request_id: string;
        };
        /**
         * @description * `VALIDATION_ERROR` - VALIDATION_ERROR
         *     * `LOCATION_NOT_FOUND` - LOCATION_NOT_FOUND
         *     * `UNSUPPORTED_LOCATION` - UNSUPPORTED_LOCATION
         *     * `AMBIGUOUS_LOCATION` - AMBIGUOUS_LOCATION
         *     * `ROUTE_NOT_FOUND` - ROUTE_NOT_FOUND
         *     * `TRIP_TOO_LONG` - TRIP_TOO_LONG
         *     * `NOT_FOUND` - NOT_FOUND
         *     * `METHOD_NOT_ALLOWED` - METHOD_NOT_ALLOWED
         *     * `RATE_LIMITED` - RATE_LIMITED
         *     * `UPSTREAM_QUOTA_EXCEEDED` - UPSTREAM_QUOTA_EXCEEDED
         *     * `UPSTREAM_UNAVAILABLE` - UPSTREAM_UNAVAILABLE
         *     * `INTERNAL` - INTERNAL
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "LOCATION_NOT_FOUND" | "UNSUPPORTED_LOCATION" | "AMBIGUOUS_LOCATION" | "ROUTE_NOT_FOUND" | "TRIP_TOO_LONG" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "RATE_LIMITED" | "UPSTREAM_QUOTA_EXCEEDED" | "UPSTREAM_UNAVAILABLE" | "INTERNAL";
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        FieldError: {
            field: string;
            message: string;
        };
        HealthResponse: {
            status: components["schemas"]["StatusEnum"];
            api_version: components["schemas"]["ApiVersionEnum"];
        };
        /**
         * @description * `ok` - ok
         * @enum {string}
         */
        StatusEnum: "ok";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
